buttons component created
Indra-poudel/react-sample-code pull request #3
Opened 2020-09-16 12:08 UTC by subashlama

created buttons components but had issues with working with icons...need suggestions...

2020-09-16 14:38 UTC, Indra-poudel requested changes

2020-09-16 14:38 UTC, Indra-poudel commented on src/components/commons/Buttons/cv_buttons.css
> +} */
let's try to remove unnecessary comments.

2020-09-16 14:38 UTC, Indra-poudel commented on src/components/commons/Buttons/cv_buttons.tsx
> +  text?: string;
i think the button should have a label. so making text optional props might not make sense. rather than text, it should be  label.

2020-09-16 14:38 UTC, Indra-poudel commented on src/components/commons/Buttons/cv_buttons.tsx
> +  iconType?: string;
```
Icon: React.node
```
We need to pass the icon as a props child or pass icon as a render from props

2020-09-16 14:38 UTC, Indra-poudel commented on src/components/commons/Buttons/cv_buttons.tsx
> +  };
nice try but, but need to change:smiley_cat:

2020-09-16 14:38 UTC, Indra-poudel commented on src/components/commons/Buttons/index.ts
> +import CV_Buttons from './cv_buttons';
CaseCase not snakeCase

2020-09-16 14:38 UTC, Indra-poudel commented on src/constants/cv-buttons-box.ts
> +  Email: '^^',
:smile: nice Icon

2020-09-16 14:38 UTC, Indra-poudel commented on src/pages/component-kit/component-kit.tsx
> +import { CV_BUTTON_TYPES } from 'src/constants/cv-buttons-box';
ladder format

2020-09-16 14:42 UTC, Indra-poudel commented
> created buttons components but had issues with working with icons...need suggestions...

@subashlama let do best practice from the beginning. The description of PR should look clean and clear. Example

### Description
- [x] something changes made
- [ ]  this is incompleted

### Additional Changes
- [x] need to make changes in other components

### Screenshot
 .... screenshot or .gif of work you have done since we are doing frontend so it will be easier to figure out the task you have done :-)

2020-09-16 15:50 UTC, Indra-poudel requested changes

2020-09-16 15:50 UTC, Indra-poudel commented on src/components/commons/Buttons/cv_buttons.tsx
> +  type?: string;
forget to add onClick

2020-09-16 15:56 UTC, Indra-poudel commented
react-file : should be CamelCase
css file : snake case
Constant name : ABC_DEF 
Component name : CamelCase ex <Abc/>
interface Name: CameCase ex ButtonProps
Css className : should be like cv_button_btn_wrapper rather than btn_wrapper

2020-09-18 14:17 UTC, indra-1998 requested changes

2020-09-18 14:17 UTC, indra-1998 commented on src/components/commons/Buttons/cv-buttons.tsx
> +  onClick: (textboxText: string) => void;
textboxText :thinking: not making sense to me
``` js
onClick: (buttonLabel: string)=> void;
```

2020-09-18 14:17 UTC, indra-1998 commented on src/components/commons/Buttons/cv-buttons.tsx
> +  label?: string;
label shouldn't be optional props
```js
label: string;
```

2020-09-18 14:17 UTC, indra-1998 commented on src/components/commons/Buttons/cv-buttons.tsx
> +  };
nice :+1:

2020-09-18 14:17 UTC, indra-1998 commented on src/components/commons/Buttons/cv-buttons.tsx
> +        );
I think you got confused here.. let discuss it how to implement

2020-09-27 02:52 UTC, Indra-poudel requested changes

2020-09-27 02:52 UTC, Indra-poudel commented on src/components/commons/Buttons/cv-buttons.tsx
> +import './cv_buttons.css';
separate library import and internal project import

```js
import React from 'react';
import { useTranslation } from 'react-i18next';
import { FaBug, FaCoffee, FaExternalLinkAlt, FaFileExport, FaFileImport, FaPlus } from 'react-icons/fa';

import './cv_buttons.css';
import { CV_BUTTON_TYPES } from 'src/constants/cv-buttons-box';
```

2020-09-27 02:52 UTC, Indra-poudel commented on src/components/commons/Buttons/cv-buttons.tsx
> +  label?: string;
make label compulsory props
```js
label: string;
```

2020-09-27 02:52 UTC, Indra-poudel commented on src/components/commons/Buttons/cv-buttons.tsx
> +  }
we shouldn't make switch condition for the icon types button... we need to pass icon from props

``` js
      case CV_BUTTON_TYPES.SECONDARY:
        return (
          <button className="normal-btn btn-secondary" onClick={onButtonClicked}>
         <span>{props.icon} </span>  <span> {props.label} </span>
          </button>
        );
      case CV_BUTTON_TYPES.EXPORT:
        return (
          <button className="normal-btn btn-secondary" onClick={onButtonClicked}>
            <span>
              <FaFileExport />
            </span>
            {props.label}
          </button>
        );
      
      default:
        return (
          <button className="normal-btn normal" onClick={onButtonClicked}>
            {props.label}
          </button>
        );
    }
  }
```

2020-09-27 15:24 UTC, Indra-poudel approved these changes

2020-09-27 15:25 UTC, merged